#!/bin/bash

MAIN_LOCATION=./compiler2/main.py

LLVM_LINK_LOCATION="llvm-link-${LLVM_VERSION}"
CLANG_LOCATION="clang-${LLVM_VERSION}"

if ! command -v ${LLVM_LINK_LOCATION} 2>&1 >/dev/null
then
    echo "${LLVM_LINK_LOCATION} could not be found. Make sure the llvm toolchain is installed and supply the correct version (e.g. LLVM_VERSION='15')"
    exit 1
fi

if ! command -v ${CLANG_LOCATION} 2>&1 >/dev/null
then
    echo "${CLANG_LOCATION} could not be found. Make sure the clang toolchain is installed and supply the correct version (e.g. LLVM_VERSION='15')"
    exit 1
fi

LLVM_VERSION="${LLVM_VERSION}" python3 ${MAIN_LOCATION} "$@"